### ISSUE TITLE
flushExpired doesn't work

### ISSUE THREAD

**Issue by depiction** [pamelafox/lscache#63] opened 2016-09-26 14:07 UTC
I have local storage items that are set to expire within a day (some after 10 minutes, others at midnight). LS items existed on Friday. It's now Monday so calling lscache.flushExpired() should clear all of them, but calling it does nothing. lscache.flush() works, but I only want to flush expired items.

**Comment by ridergoster** [comment] 2016-09-27 14:18
Hi,

flushExpired works for me... Maybe the problem is when you set the date ? Can you see your localstorage ? you should have a key with a suffix 'cacheexpiration' containing the timestamp. you should convert it to see if your date was good

**Comment by pamelafox** [comment] 2017-02-24 22:53
I'm going to close this issue until we have further steps for replication / details. @ridergoster Thanks for providing debug tips.

**Closed by pamelafox** 2017-02-24 22:53 UTC
